# Aufgabenstellung 

## Thema des Seminars

- Im Zentrum steht dieses Semester die [**Conference of the Parties | COP30**](https://cop30.br/en), die vom 10. November 2025 bis zum 21. November in Belém (Brasilien) stattfindet

- Im Seminar setzen wir uns mit den Themen der Konferenz, den Positionen der Staaten sowie dem (noch offenen) Gesamtergebnis auseinander.

- Aus diesem Themenkomplex entwickeln Sie Ihre Seminararbeit

## Prüfungsleistung(en)

- **Seminararbeit** als *Einzel*leistung (!) (75%)
- Umfang ca 10-12 Seiten

- **Präsentation** des Arbeitsstandes/der Kernergebnisse (25%)
- Selbständige Recherche geeigneter Literatur in angemessenem Umfang
- Berücksichtigung von mindestens drei englischsprachigen wissenschaftlichen Texten  
- Präsentation des Arbeitsstandes/der Kernergebnisse (25%)


- **Abgabe** der Seminararbeiten bis **18.12.2025**

- Terminierung der Referate ist derzeit noch offen


## Themen der Seminararbeiten

1. Der Paris-Prozess zehn Jahre danach: Effektivität und ökonomische Anreize internationaler Klimaverträge

1. Der Stand der Verhandlungen zu Artikel 6 des Pariser Abkommens: Ökonomische Potenziale und Risiken internationaler Kohlenstoffmärkte (Art. 6.2 und 6.4).

1. Globale Klimafinanzierung nach der “Baku-to-Belém Roadmap”: Neue Ansätze für eine faire Lastenteilung

1. Das Verhältnis von Klimaschutz und wirtschaftlicher Entwicklung im globalen Süden

1. Internationale Klimapolitik als öffentliches Gut: Spieltheoretische Analyse globaler Kooperation und Trittbrettfahrerverhalten

1. Die Rolle der EU auf der COP 30: Zwischen Green Deal, Carbon Border Adjustment Mechanism (CBAM) und globaler Verantwortung

1. Climate Clubs und ihre ökonomische Wirkung: Analyse der Kooperationsstrategien für ambitionierte NDCs außerhalb des UNFCCC-Rahmens.

1. Anreize und Rahmenbedingungen zur klimagerechten Nutzung und Gestaltung ausgewählter Räume



## Rahmenbedingungen

- Sitzungen im Plenum
- Einzelarbeit/ Einzelgespräche  
- Gruppenarbeit  
- ~~Peer Review~~

## Abschlusspräsentation

- **Zeitlicher Umfang**: ca 15 Minuten

- **Inhalt**: Kernaussagen Ihrer Ausarbeitung

- **Show**: Demonstration Ihrer Kompetenz  
  - Analytische Fähigkeiten
  - Aufbereitung von Informationen
  - Rechercheleistung
  - $\dots$