# Hintergrund 

## Institutionalisierung des internationalen Klimaschutzes

- Die wesentlichen Bausteine des **Pariser Abkommens** sind die Begrenzung der Erderwärmung, regelmäßige nationale Zielsetzungen, Anpassung an den Klimawandel, Klimafinanzierung, Transparenz und internationale Zusammenarbeit.

- **Hauptziele**  

  - **Begrenzung des globalen Temperaturanstiegs** auf deutlich unter 2 °C, möglichst auf 1,5 °C gegenüber dem vorindustriellen Niveau.

  - **Langfristige Treibhausgasneutralität**, also Gleichgewicht zwischen Emissionen und deren Entzug durch Senken (Wälder, Moore etc.)
  

- **Nationale Beiträge (NDCs)** 
  
  - Alle Staaten müssen eigene Klimaschutzziele („Nationally Determined Contributions“, NDCs) entwickeln und regelmäßig verschärfen.

  - Rechenschafts- und Überprüfungsmechanismen durch regelmäßige globale Bestandsaufnahmen („Global Stocktake“ alle fünf Jahre).

- **Anpassung und Widerstandsfähigkeit**  

  - Ausbau der Anpassungsfähigkeit an den Klimawandel und Stärkung der Widerstandsfähigkeit, besonders für Entwicklungsländer.

  - Mechanismen zu Verlusten und Schäden durch Klimafolgen sind ebenfalls Bestandteil.

- **Klimafinanzierung**  

  - Umlenkung globaler Finanzströme in nachhaltige Investitionen.

  - Industrieländer sollen Entwicklungsländer beim Klimaschutz und der Anpassung unterstützen – Ziel: jährliche Mobilisierung von mindestens 100 Mrd. US-Dollar ab 2020.
  
  
- **Transparenz und Kontrolle**

  - Strenge Berichtspflichten und Kontrollverfahren für Fortschritte und die Umsetzung der Maßnahmen.

  - Ein robustes System für Transparenz und Verantwortung, um Ambitionen stetig zu erhöhen
  
  
  
  
## Die COP

## Der Emissions Gap Report 2024

<embed src="https://www.undp.org/sites/g/files/zskgke326/files/2025-01/egr2024.pdf" type="application/pdf" width="100%" height="700px">

## Der Emissions Gap Report 2025

[Hier](https://wedocs.unep.org/handle/20.500.11822/48854;jsessionid=71939FA031A32DE1C1F2123F2F72345A)