# Ablauf der Sitzungen

## 14.10.25 {-}

- [ ] Organisatorisches
- [ ] Formalia der Seminararbeit
- [ ] Wissenschaftliches Schreiben
- [ ] Interesse für bestimmte Themen?

## 21.10.25 {-}

- [ ] Vertiefung des thematischen Hintergrunds
- [ ] Vorstellung der Themen
- [ ] Mechanismus der Themenvergabe

## 28.10.25 {-}

## 4.11.25 {-}

## 11.11.25 {-}

## 18.11.25 {-}

## 25.11.25 {-}

- Orga Zwischenvorträge

- Ergebnisse der COP 30

- Raum für Gespräche

## 2.12.25 {-}

### Zwischenvorträge {-}

### Gruppenarbeiten {-}

Was ist Ihrer Auffassung nach zu tun, damit es interanational zu den erforderlichen Emissionsreduktionen kommt?

- Globales Organ/Vereinigung: "Klimadiktatur"; Staaten müssen zu Emissionsreduktionen gezwungen werden. Verbindliche Vorgaben. Staaten muss es unmöglich gemacht werden, auszutreten [Anmerkung JV: Das ist der Weg nach Thomas Hobbes]

- Konkrete Zielsetzung und Zwischenziele 

- Finanzierungsstrategie, die auch unterschiedliche Betroffenheiten und Möglichkeiten widerspiegeln

- Forschung und Entwicklung für zukundtsorientierte Maßnahmen

- Das Denken in Wahlperioden muss überwunden werden

- In diesem Sinne müssen Staaten Souveränität verlieren

- Bildungsarbeit



Was ist Ihrer Auffassung nach zu tun, damit alle Länder die Möglichkeit haben, sich an die Folgen des Klimawandels anzupassen?

- Auswirkungnen in Küstenregionen sehr stark. Migrationsreaktionen

- Umverteilung von reicheren zu ärmeren Ländern

- Innovationen zur Entnahme von CO$_2$ aus der Atmosphäre

- Umgang mit gesellschaftlichen Spannungen/Krisenreselienz


## 9.12.25 {-}

- Vorträge

- Bitte erarbeiten

  - https://ourworldindata.org/less-meat-or-sustainable-meat
  
  - https://ourworldindata.org/co2-gdp-decoupling
  
  - https://ourworldindata.org/co2-emissions-metrics

## 16.12.25 {.unnumbered}

## 13.1.26 {-}

## 20.1.26 {-}

## 27.1.26 {-}

